Document: fteproxy
Title: Debian fteproxy Manual
Author: <insert document author here>
Abstract: This manual describes what fteproxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fteproxy/fteproxy.sgml.gz

Format: postscript
Files: /usr/share/doc/fteproxy/fteproxy.ps.gz

Format: text
Files: /usr/share/doc/fteproxy/fteproxy.text.gz

Format: HTML
Index: /usr/share/doc/fteproxy/html/index.html
Files: /usr/share/doc/fteproxy/html/*.html
